run:
  timeout: 3m
  tests: true

linters:
  enable:
    - govet
    - revive        # modern replacement for golint-style checks
    - gofmt
    - goimports
    - staticcheck
    - ineffassign
    - gosimple
    - errcheck

linters-settings:
  revive:
    severity: warning
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: errorf
      - name: exported
      - name: indent-error-flow
      - name: package-comments
      - name: receiver-naming

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
